version: '3.1'
services:
  stats-server:
    build: ./ewm-stats-service/stats-server
    image: stats-server:latest
    container_name: stats-server

    ports:
      - "9090:9090"
      - "9091:9091"

    depends_on:
      - stats-service-db
    environment:
      - STAT_URL_DB=jdbc:postgresql://state_server-db:5432/stat_db
      - STAT_USERNAME_DB=postgres1
      - STAT_PASSWORD_DB=postgres1


  stats_service-db:
    image: postgres:14-alpine
    container_name: stats-server-db
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres1


  ewm-service:
    build: ./ewm-main-service
    image: ewm-service:latest
    container_name: ewm-service

    ports:
      - "8080:8080"
      - "8081:8081"

    depends_on:
      - ewm-db
    environment:
      - MAIN_DB=jdbc:postgresql://postgres-main-db:5432/ewm_db
      - MAIN_USER=postgres
      - MAIN_PASSWORD=postgres

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-main-db
    ports:
      - "6464:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres